# pyright: strict


ERR_MSG_MAX_LEN = 300

CONTENT__USER_AGENT = "skill4searchSpecies/1.0 "

STRUCT_WIDTH = 600
STRUCT_HEIGHT = 600
TEXT_WIDTH = 900
DIVIDER_WIDTH = 4
CARD_HEIGHT = STRUCT_HEIGHT + DIVIDER_WIDTH
CARD_WIDTH = STRUCT_WIDTH + TEXT_WIDTH + DIVIDER_WIDTH

COLUMNS = 2

FONT_SIZE = 28
CHARS_PER_LINE = 48

TEXT_OFFEST_X = 40
TEXT_OFFEST_Y = 40
